// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btqhkqletkylwrunclrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0cWhrcWxldGt5bHdydW5jbHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzUzMDYsImV4cCI6MjA2NzU1MTMwNn0.3Lrexbu51ryghGSEttpwZZWD2fHfb6Jk7lcw3FHuh0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});